### PR TITLE
Added extendSchema method.

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
I've added a extendSchema method which takes a schema file, and recursively merges it with the current schema. Very simple, but it works.
Should help address #1.

If anything needs to be revised, let me know.

(Worth noting that the commit also cleans up the trailing white space in the edited file)

### CODE REVIEW

**Comment by alexweissman** [comment]
I kind of wonder if this should be split into two classes:

- `RequestSchemaJsonReader`: responsible for reading JSON files, possibly linting using Seldaek's library, etc, and then can produce a PHP array as output;
- `RequestSchema`: represents a complete schema, completely independent of file representation, and can merge in additional values as needed.

So then you'd do something like:

```
$reader = new RequestSchemaJsonReader($filename);
$schema = new RequestSchema($reader->get());
$reader2 = new RequestSchemaJsonReader($anotherFilename);
$schema->extend(reader2->get());
$someMoreStuff = [
    "puppies" => [
        ...
    ]
];
$schema->extend($someMoreStuff);
```

This would decouple the storage representation from the schema class.  What do you think?

**Comment by lcharette** [comment]
if `$reader` has no used after or any other method, might as well do `$schema = new RequestSchema($filename);` directly (same goes for `->extend` )

**Comment by alexweissman** [comment]
Yeah but, what if you want to add/extend rules from some other source, like a YAML file, or even just a raw PHP array?

**Comment by lcharette** [comment]
True.

**Comment by alexweissman** [comment]
It does make the process of loading a simple request schema more complicated though, as now it requires two lines of code instead of one.  We could always set up a facade, so you could do `RequestSchema::fromJsonFile()` or something.

**Comment by Silic0nS0ldier** [comment]
I like the idea of additional schema file type support. Means that everyone can work with what they consider to be "best".

Provided that on the other side of this, there is a way to easily extend the schema. 😄

**Comment by alexweissman** [comment]
This is now possible in 4.1.

To merge multiple schema files:
```
$loader = new YamlFileLoader(['/path/to/base.yaml', '/path/to/extension.yaml']);
$schema = new RequestSchemaRepository($loader->load());
```

To extend from an array:
```
$loader = new YamlFileLoader('/path/to/base.yaml');
$schema = new RequestSchemaRepository($loader->load());
$schema->mergeItems([
    "puppies" => [
        ...
    ]
];
```

Basically, `YamlFileLoader` can merge together as many YAML files as you want, and `load()` generates the final result.  Check out the documentation for [`userfrosting/support`](https://github.com/userfrosting/support#loaders).

**Comment by Silic0nS0ldier** [comment]
Not exactly what I was hoping for to be honest. While technically what this pull request introduces can be achieved with the updates, there will be some code duplication. (potentially huge amounts of duplication is certain scenarios)

**Comment by alexweissman** [comment]
You can always wrap some of these objects in a helper class, if you really need...

**Pull request closed without merging**
